### ISSUE TITLE
Intermittent error: "duplicated values in labels"

### ISSUE THREAD

**Issue by tgravelle** [gdemin/expss#104]
Hello!

In using expss to tabulate survey data, I am receiving the error message below intermittently. By "intermittent" I mean that when this error occurs, I can simply re-run the example code (also below) and often obtain the desired tabulation. For context, all of the columns in data.2 being tabulated are factors (I am not at liberty to share the data).

```
Error in set_val_lab.default(x, value, add = FALSE) : 
  'set_val_lab' - duplicated values in labels:
```

```
banner_tables <- data.2 %>%
  tab_weight(weight = weight) %>%
  tab_total_row_position("above") %>%
  tab_cols(total(), gender, age, education, race.ethn, region) %>%
  tab_cells(Q21.0 %to% Q21.11) %>% tab_stat_cpct() %>%
  tab_cells(Q22.0 %to% Q22.13) %>% tab_stat_cpct() %>%
  tab_cells(Q23.0 %to% Q23.6) %>% tab_stat_cpct() %>%
  tab_cells(Q24.0, Q24.1, Q24.2) %>% tab_stat_cpct() %>%
  tab_cells(Q25.0, Q25.1, Q25.2) %>% tab_stat_cpct() %>%
  tab_pivot() %>%
  as_tibble()
```

This is rather a strange behavior that I haven't encountered with expss before. Why would unchanged code produce varying results -- sometimes returning an error message and sometimes returning the desired tabulation?

Thank you in advance for any insight on what might be causing this.

**Comment by gdemin** [comment]
Hello!
Where do you get your data from? Which function do you use to load the data?
Could you apply the function below to your dataset? It will detect factors with duplicated levels:

```R
dupl_levels = function(df){
    res = lapply(df, attr, 'levels')
    dupl_levels = sapply(res, anyDuplicated)
    res[dupl_levels>0]
}
```

**Comment by gdemin** [comment]
Could you provide the result of `str` on each variable which is used in your code for the table?

**Comment by gdemin** [comment]
The same as #107.
Could you run the `sessionInfo()` on your system and place the results here?

**Comment by gdemin** [comment]
The same as #107. Close as duplicated.
