### ISSUE TITLE
'do_repeat' functionality

### ISSUE THREAD

**Issue by Berghuette** [gdemin/expss#106]
"'do_repeat' functionality is deprecated because it seems no one need it."  -> I think it would help to keep the function for people who know the SPSS command DO REPEAT .. END REPEAT.

**Comment by gdemin** [comment]
Could you provide sveral snippets of your code with `do_repeat`, please?
I will save this function but its code is unnecessarily complicated. With your examples I will try to refactor it without breaking things.
