### ISSUE TITLE
Table rendering question

### ISSUE THREAD

**Issue by i98512** [gdemin/expss#12]
Hello Greg, 

I am using R studio 1.1.456 & R 3.5.1.

I tried to repeat your example (cro(mtcars$am, mtcars$vs)) after installing htmlTable, data.table, expss and loading them. But the rendering output (as below) looks very different from yours.  Could you please help? Thank you.

|                       |                        |   Engine   |                          |
|                       |                        | V-engine | Straight engine |
|  ------------   |   ------------    |   --------  |   ---------------  |
| Transmission |    Automatic    |           12 |                        7 |
|                       |       Manual     |             6 |                        7 |
|                       | #Total cases   |           18 |                      14 |

**Comment by gdemin** [comment]
Hi!
By default results are outputted to the console. To output table to RStudio viewer try to execute `expss_output_viewer()`  before running examples. 
Or, you can use knitr. Create new document: File -> New File -> R Markdown and paste examples inside code chunk. After that knit to html.

**Comment by i98512** [comment]
Thank you so much for the fast & helpful response. And of course, thank you for developing the package.
