### ISSUE TITLE
Installing problem

### ISSUE THREAD

**Issue by zelihay** [gdemin/expss#14]
Hi Mr. Gregory,
Thanks for this useful package. I am trying to find another program instead of SPSS for tabulation. I hope this package would meet our needs. 

I am using Ubuntu 16.04 and RStudio 3.5. I must say I am new in R. 

When I write **install.packages ("expss")** on RStudio console, I get this error:
_Warning in install.packages :
  installation of package ‘expss’ had non-zero exit status_

Should I install another version of R? Is there any other way to install this package?
Best regards,
Zeliha

**Comment by gdemin** [comment]
Hi, Zeliha,
Are there any other messages in the console during installation?
Could you try install all required packages one by one? For this you need to run the following code line by line:

```
install.packages("magrittr")
install.packages("htmlTable")
install.packages("matrixStats")
install.packages("data.table")
install.packages("expss")
```
Are all of them before 'expss' were installed successfully?

**Comment by zelihay** [comment]
Hi Mr. Gregory

Thanks for quick reply.
I've done what you said, and I got two error messages for **htmlTable** and **expss**

**DONE** (magrittr)
**DONE** (matrixStats)
**DONE** (data.table)

**install.packages("htmlTable")**

_* installing *source* package ‘htmlTable’ ...
** package ‘htmlTable’ successfully unpacked and MD5 sums checked
** R
** data
** inst
** byte-compile and prepare package for lazy loading
Error : package ‘checkmate’ was installed by an R version with different internals; it needs to be reinstalled for use with this R version
ERROR: lazy loading failed for package ‘htmlTable’
* removing ‘/home/zeliha/R/x86_64-pc-linux-gnu-library/3.5/htmlTable’
Warning in install.packages :
  installation of package ‘htmlTable’ had non-zero exit status_

**install.packages("expss")**

_* installing *source* package ‘expss’ ...
** package ‘expss’ successfully unpacked and MD5 sums checked
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace ‘htmlTable’ 1.9 is being loaded, but >= 1.11.0 is required
ERROR: lazy loading failed for package ‘expss’
* removing ‘/home/zeliha/R/x86_64-pc-linux-gnu-library/3.5/expss’
* restoring previous ‘/home/zeliha/R/x86_64-pc-linux-gnu-library/3.5/expss’
Warning in install.packages :
  installation of package ‘expss’ had non-zero exit status_

**Comment by gdemin** [comment]
It seems you need to reinstall 'checkmate' package.
Please, execute the following code:
```
install.packages("checkmate")
install.packages("htmlTable")
install.packages("expss")
```
Is 'expss'  package installed successfully?

**Comment by zelihay** [comment]
Mr. Gregory,

Thanks for your help. There is a problem with htmlTable. Here are messages;

**DONE (checkmate)**

**> install.packages("htmlTable")**

Error : package ‘htmltools’ was installed by an R version with different internals; it needs to be reinstalled for use with this R version
ERROR: lazy loading failed for package ‘htmlTable’
* removing ‘/home/zeliha/R/x86_64-pc-linux-gnu-library/3.5/htmlTable’
Warning in install.packages :
  installation of package ‘htmlTable’ had non-zero exit status

**> install.packages("htmlTable")**

* installing *source* package ‘expss’ ...
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace ‘htmlTable’ 1.9 is being loaded, but >= 1.11.0 is required
ERROR: lazy loading failed for package ‘expss’
* removing ‘/home/zeliha/R/x86_64-pc-linux-gnu-library/3.5/expss’
* restoring previous ‘/home/zeliha/R/x86_64-pc-linux-gnu-library/3.5/expss’
Warning in install.packages :
  installation of package ‘expss’ had non-zero exit status

**Comment by gdemin** [comment]
Let's try to reinstall all packages for htmlTable:
```
install.packages("stringr")
install.packages("knitr")
install.packages("checkmate")
install.packages("htmlwidgets")
install.packages("htmltools")
install.packages("htmlTable")
install.packages("expss")
```

**Comment by gdemin** [comment]
You are welcome. Usually, packages installation is not so painful. R3.5 has a lot of internal changes that's why some packages need to be reinstalled to work.
