### ISSUE TITLE
Replicate tables

### ISSUE THREAD

**Issue by robertogilsaura** [gdemin/expss#15]
Hi @gdemin,

I want to ask the easier way to replicate this case...

Imagine that I have one variable, BRAND, with codes 1:4 and I need replicate a table like this, whre LIKES is a variable related with BRAND. In the questionnaire, you answer for your first BRAND and next question is LIKES of this BRAND answered. How can I reproduce the below table for every level (value) of BRAND?

I tried "criteria", "by_groups", with an R "loop"..., but I don't find the best solution for a dummies (me). I believe that it should be a more easier way to build it that I don't know.

`BRAND <- c(1,2,3,2,3,2,1,2,3,4,3,2,1,2,3,4,3,4)
LIKES <- c(1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,1)
GENDER <- c(1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2)

cis <- dataframe(GENDER,BRAND,LIKES)
    cis %>%
    tab_cells(LIKES) %>%
    tab_cols(total(), GENDER) %>% 
    tab_stat_cases() %>%
    tab_pivot()`

The output for me should be ...

BRAND ==1
table GENDER x LIKES

BRAND ==2
table GENDER x LIKES

BRAND ==3
table GENDER x LIKES

BRAND ==4
table GENDER x LIKES

Thanks for your help...

**Comment by gdemin** [comment]
Hi, @robertogilsaura 
You can use `tab_rows` or `tab_subgroup`:
```
library(expss)
BRAND <- c(1,2,3,2,3,2,1,2,3,4,3,2,1,2,3,4,3,4)
LIKES <- c(1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,1)
GENDER <- c(1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2)

cis <- data.frame(GENDER,BRAND,LIKES)
# with tab_rows
cis %>%
    tab_cells(LIKES) %>%
    tab_cols(total(), GENDER) %>%
    tab_rows(BRAND) %>% 
    tab_stat_cases() %>%
    tab_pivot()
 # |       |    |       |              | #Total | GENDER |    |
 # |       |    |       |              |        |      1 |  2 |
 # | ----- | -- | ----- | ------------ | ------ | ------ | -- |
 # | BRAND |  1 | LIKES |            1 |      3 |      2 |  1 |
 # |       |    |       |            2 |        |        |    |
 # |       |    |       | #Total cases |      3 |      2 |  1 |
 # |       |  2 | LIKES |            1 |        |        |    |
 # |       |    |       |            2 |      6 |      4 |  2 |
 # |       |    |       | #Total cases |      6 |      4 |  2 |
 # |       |  3 | LIKES |            1 |      6 |      3 |  3 |
 # |       |    |       |            2 |        |        |    |
 # |       |    |       | #Total cases |      6 |      3 |  3 |
 # |       |  4 | LIKES |            1 |      1 |        |  1 |
 # |       |    |       |            2 |      2 |        |  2 |
 # |       |    |       | #Total cases |      3 |        |  3 |

# and with tab_subgroup
for(i in sort(unique(cis$BRAND))){
    cis %>%
        tab_cells(LIKES) %>%
        tab_cols(total(), GENDER) %>%
        tab_subgroup(BRAND == i) %>% 
        tab_stat_cases() %>%
        tab_pivot() %>% 
        set_caption(sprintf("BRAND == %s", i)) %>% 
        print()
}
 # BRAND == 1                                                  
 # |       |              | #Total | GENDER |    |
 # |       |              |        |      1 |  2 |
 # | ----- | ------------ | ------ | ------ | -- |
 # | LIKES |            1 |      3 |      2 |  1 |
 # |       | #Total cases |      3 |      2 |  1 |
 # BRAND == 2                                                  
 # |       |              | #Total | GENDER |    |
 # |       |              |        |      1 |  2 |
 # | ----- | ------------ | ------ | ------ | -- |
 # | LIKES |            2 |      6 |      4 |  2 |
 # |       | #Total cases |      6 |      4 |  2 |
 # BRAND == 3                                                  
 # |       |              | #Total | GENDER |    |
 # |       |              |        |      1 |  2 |
 # | ----- | ------------ | ------ | ------ | -- |
 # | LIKES |            1 |      6 |      3 |  3 |
 # |       | #Total cases |      6 |      3 |  3 |
 # BRAND == 4                                             
 # |       |              | #Total | GENDER |
 # |       |              |        |      2 |
 # | ----- | ------------ | ------ | ------ |
 # | LIKES |            1 |      1 |      1 |
 # |       |            2 |      2 |      2 |
 # |       | #Total cases |      3 |      3 |

**Comment by robertogilsaura** [comment]
hi @gdemin 

a lot of thanks.... second way was the output that I was looking for...

Great package expss!!!!

**Comment by robertogilsaura** [comment]
Hi @gdemin 

I'm deploying the process in rmarkdown, but I didn't get print tables in expss_output_viewer() mode. 

This is my chunk 

```{r}
suppressMessages(library(expss, quietly=TRUE))
data <- suppressMessages(read_spss("~/_datos/92.expss/ems2018.sav"))
options(scipen=5,width=255)
j <- val_lab(data$ZONA) 
for (i in sort(unique(data$ZONA)))
    {
data %>%
        tab_cells(P15) %>%
        tab_cols(total(), SEXO) %>%
        tab_subgroup(ZONA == i) %>% 
        tab_stat_cpct() %>%
        tab_cells(na_if(P15, gt(5))) %>% 
        tab_stat_mean_sd_n() %>%
        tab_pivot(stat_position = "inside_rows") %>% 
        set_caption(paste("|",attr(j,"names")[i])) %>% 
        print()
}
```
Table always are in text mode in the final html output, but I dont find the way for print in viewer mode. If I write expss_output_viewer() into de function, output is HTML code.

Thank you in advance for your help ... 

[ems2018.zip](https://github.com/gdemin/expss/files/2657204/ems2018.zip)

**Comment by gdemin** [comment]
Hmm... It seems it is rather tricky to print something with loops in the RMarkdown. Solution from [here](https://stackoverflow.com/questions/38232719/r-markdown-and-htmltable-how-to-generate-html-tables-in-a-loop-in-r-markdown): 
```R
suppressMessages(library(expss, quietly=TRUE))
data <- suppressMessages(read_spss("~/_datos/92.expss/ems2018.sav"))
options(scipen=5,width=255)
j <- val_lab(data$ZONA) 
for (i in sort(unique(data$ZONA)))
    {
data %>%
        tab_cells(P15) %>%
        tab_cols(total(), SEXO) %>%
        tab_subgroup(ZONA == i) %>% 
        tab_stat_cpct() %>%
        tab_cells(na_if(P15, gt(5))) %>% 
        tab_stat_mean_sd_n() %>%
        tab_pivot(stat_position = "inside_rows") %>% 
        set_caption(paste("|",attr(j,"names")[i])) %>% 
        htmlTable() %>%
        print()
}
```
Note that you need to add `results='asis'` to your chunk options.

**Comment by robertogilsaura** [comment]
​Hi @gdemin

Success, great  !!!! runs properly... I would never have found the solution !!!

Here leave code for help someone with same problem... Note that is a chunk 
{r, results='asis'}
j <- val_lab(data$D)
for (i in sort(unique(data$D)))
    {
output <- data %>%
        tab_cells(A) %>%
        tab_weight(B) %>% 
        tab_cols(total(), C) %>%
        tab_subgroup(D== i) %>% 
        tab_stat_cpct() %>%
        tab_cells(na_if(A, gt(5))) %>%
        tab_stat_mean_sd_n() %>%
        tab_pivot(stat_position = "inside_rows") %>% 
        set_caption(attr(j,"names")[i])
        print(htmlTable(output))
}
