### ISSUE TITLE
Chi Square Cell Test

### ISSUE THREAD

**Issue by robertogilsaura** [gdemin/expss#17]
Hi @gdemin

I wanted to ask if it is possible or if it is in the EXPSS roadmap to perform the Chi Square Cell Test for a contingency table. This test is very common that is requested by companies such as TNS, GFK and Nielsen. Let's say it's a basic specification next to the independence counter obtained in the table (possible with tab_last_sig_cases).

In my case, I worked with Quantum (basic) and with Barbwin and SPSS (test not available in user interface). I attach documentation that was delivered to me at the time by Kantar TNS, where formula is specified and it can be seen that it is a specification for a 2 * 2 table of the general Chi test. (SPSS doc)

The particular thing is that it is applied to each cell of the table i * j, constructing the table 2 * 2 derived from each cell, the p-value is obtained and the cell is marked if the p-value is significant.

[Chi-Square Cell Test.pdf](https://github.com/gdemin/expss/files/2681281/Chi-Square.Cell.Test.pdf)

Thanks in advance.

P.S. If you think it is necessary, I can send calculation examples in EXCEL.

**Comment by gdemin** [comment]
Hi @robertogilsaura 
Ok, I will include it in the roadmap and will try to implement this test in January/February release. 
Excel examples will be helpful.

**Comment by robertogilsaura** [comment]
Hi @gdemin

I send toy an Excel file with example for computing chisq cell test in a contingency crosstabs.

It's very simple. There are computing with Excel functions, with R test and manually.

blue, raw data
red, raw data for totals
green, manual test

THE PROCESS
0) Compute the crosstab
1) Create for every cell in crosstab, a new table with value to test (blue) and complementary (red (totals) and black)
2) In manually test, compute the expected frequency for this new table
3) Compute chi2 value for every cell in 2*2 table (observed-expected)^2/expected
4) Summatory for four chi2 values is chi2 for table
5) Show the original table, but use < if the Chi2 value for table is significative and percentage (column) is less than total marginal percentage; use > if the Chi2 value for table is significative and percentage (column) is greater than total marginal percentage. Each software presents the mark to its own way ...

Normally, this marks are showed with column percentage.

Chisq test is the same formula in expss (like R stats) without Yates' correction. It's not error (2 * 2 tables, normally have Yates' correction).

I hope to be helpful ... Thanks a lot

[Example ChiSquareCellTest.xlsx](https://github.com/gdemin/expss/files/2683817/Example.ChiSquareCellTest.xlsx)
