### ISSUE TITLE
Align with htmlTable

### ISSUE THREAD

**Issue by robertogilsaura** [gdemin/expss#20]
Hi @gdemin 

I tried to align to center all columns in a table (except col 1), using your suggestion for htmlTable ...

_`htmlTable(tab.gen, css.cell = c("width: 200px", rep("width: 75px", ncol(table.gen) - 1)))`_

with 

_`htmlTable(tab.gen, css.cell = c("width: 300px", rep("width: 75px", ncol(tab.gen) - 1)), align= paste(rep("c", ncol(tab.gen)-1), collapse = ""))`_

but I always have the same warning / error

`Error in htmlTable.default(prConvertDfFactors(x), ...) : 
  formal argument "align" matched by multiple actual arguments
Calls: <Anonymous> ... htmlTable.etable -> htmlTable -> htmlTable.data.frame`

What is the correct way for deploy alignment in tables?

Thanks in advance @gdemin

**Comment by gdemin** [comment]
Hi, @robertogilsaura 

Yes, there was internally calculated alignment which conflicts with `align` argument. I fixed it in the development version. You can install it with  `devtools::install_git("https://github.com/gdemin/expss", ref = "develop")` if you want. For installation you need `devtools` package and RTools - https://cran.rstudio.com/bin/windows/Rtools/

**Comment by robertogilsaura** [comment]
Hi @gdemin

Success!!!

Thank a lot ...
