### ISSUE TITLE
Mix cases & stats in same table

### ISSUE THREAD

**Issue by robertogilsaura** [gdemin/expss#22]
Hello,

I'm trying to mix stat_cases and  stat_mean / sd in the same table. Output is ok, but the number of decimals after the value in cases is equal to number of decimals after the value in mean or sd.

Is it possible getting the same table, but with 0 decimals in stat_cases and one decimal in mean or sd?

I tried with "expss_options" or "expss.options", but I think that I located in bad place argument...

P28 <- sample(c(1:10,98,99), 625, replace=TRUE)
P32 <- sample(1:5, 625, replace=TRUE)
data <- data.frame(P28, P32)
data %>%
    tab_cells(P28) %>%
    tab_cols(total(), P32) %>%
    tab_stat_cases() %>% 
    tab_cells(P28=na_if(P28, gt(10))) %>% 
    tab_stat_fun("Media" = w_mean, "Sd" = w_sd) %>%
    tab_pivot(stat_position = "inside_rows")

Thanks in advance

**Comment by robertogilsaura** [comment]
Successful & wonderful ...

Thanks a lot; extraordinary work, this package every day leaves me more surprised and impressed ... in spanish words, "flipando". Happy 2019, Mr Demin [@gdemin] !!!!

**Comment by robertogilsaura** [comment]
Hi @gdemin .

I have a new question about this issue. If I can mix cases (0 digits) , pct (I would like 1 digit) and statistic measures (2 digits). **Can I distinguish between cases and percentages in the same table and use different numbers of digits?**

For example

```
#' @param tbl table, result of cro_*, tab_*
#' @param zero_digits_labels function/value which return TRUE on row labels for which we want zero-digits formatting
#' @param digits integer number of digits after decimal separator
tab_format_digits = function(tbl, 
                        zero_digits_labels = fixed("#"), 
                        digits = get_expss_digits()
                        ){
        zero_digits_rows = tbl[[1]] %has% zero_digits_labels
        for(i in seq_along(tbl)[-1]){
            tbl[[i]] = ifelse(zero_digits_rows, 
                              formatC(tbl[[i]], format = "f", digits = 0),
                              formatC(tbl[[i]], format = "f", digits = digits)
                              )
        }
        tbl
}

P28 <- sample(c(1:10,98,99), 625, replace=TRUE)
P32 <- sample(1:5, 625, replace=TRUE)
data <- data.frame(P28, P32)
data %>%
    tab_cells(P28) %>%
    tab_cols(total(), P32) %>%
    tab_stat_cases() %>%
    tab_cells(P28=na_if(P28, gt(10))) %>%
    tab_stat_fun("Mean" = w_mean, "Std. dev." = w_sd) %>%
    tab_pivot(stat_position = "inside_rows") %>% 
    tab_format_digits(zero_digits_labels = !perl("Mean|Std. dev.")) # zero decimals for all rows except mean and sd
```

Thanks in advance ...

**Comment by gdemin** [comment]
Now `tab_format_digits` has semantic similair to 'recode'. So it can accept any number of conditions for digits.
```R
#' @param tbl table, result of cro_*, tab_*
#' @param ... formulas LHS is criteria which will be applied to first column of
#'   the table, RHS is desired number of digits. Each item will be formatted
#'   only once.
tab_format_digits = function(tbl, 
                             ...
){
    digit_formatter = function(digits) function(column) formatC(column, format = "f", digits = digits)
    all_args = list(...)
    from = lapply(all_args, function(frmla) {
        cond = eval.parent(frmla[[2]])
        cond(tbl[[1]])
        })
    to = lapply(all_args, function(frmla) digit_formatter(eval.parent(frmla[[3]])))
    recode(tbl[,-1]) = from_to(from, to)
    tbl
}

is_odd_item = function(x) seq_along(x) %% 2 != 0

P28 <- sample(c(1:10,98,99), 625, replace=TRUE)
P32 <- sample(1:5, 625, replace=TRUE)
data <- data.frame(P28, P32)
data %>%
    tab_cols(total(), P32) %>%
    tab_cells(P28) %>%
    tab_stat_cases() %>%
    tab_stat_cpct() %>% 
    tab_cells(P28=na_if(P28, gt(10))) %>%
    tab_stat_fun("Mean" = w_mean, "Std. dev." = w_sd) %>%
    tab_pivot(stat_position = "inside_rows") %>% 
    tab_format_digits(
        perl("#") ~ 0, # totals - zero digits
        perl("Mean|Std. dev.") ~ 2, # summary statistics - two digits
        is_odd_item ~ 0, # odd rows will be formatted with zero digits because it is number of cases
        other ~ 1 # all other values will be formatted with one digit

    ) 
```

**Comment by robertogilsaura** [comment]
Thank you very much @gdemin. The output is what I needed.

**Comment by blam3** [comment]
Hi there,

I have a problem similar to this one, except I would like my last column to have zero decimals while my mean and SD are columns that have two decimals.

Right now, my table looks like this:

![Screenshot 2020-05-03 00 32 42](https://user-images.githubusercontent.com/53319932/80898795-bcb32080-8cd5-11ea-8c91-05221fc5c504.png)

I would like my last column to be rounded to the nearest whole number. I've tried modifying the above solution to fit my needs, but I'm new to programming and I'm having trouble understanding the syntax. Thank you.

**Comment by gdemin** [comment]
@blam3 Could you provide code for reproducing your table?

**Comment by blam3** [comment]
@gdemin  Yes. Here it is:

expss_digits(digits = 2)

subscales %>%
  tab_cells(male_subscore, female_subscore, POC_subscore, white_subscore,
            white_women_subscale, white_men_subscale, POC_women_subscore,
            POC_men_subscore, data.Overall_Reconition_Mean) %>% 
  tab_cols(total(label = '')) %>% 
  tab_stat_fun("Mean Subscale" = w_mean, "SD" = w_sd, "Median Subscale" = w_median, method = list) %>%
  tab_pivot(stat_position = "inside_rows")

**Comment by gdemin** [comment]
The simples solution is:
```R

expss_digits(digits = 2)

subscales %>%
tab_cells(male_subscore, female_subscore, POC_subscore, white_subscore,
white_women_subscale, white_men_subscale, POC_women_subscore,
POC_men_subscore, data.Overall_Reconition_Mean) %>%
tab_cols(total(label = '')) %>%
tab_stat_fun("Mean Subscale" = w_mean, "SD" = w_sd, "Median Subscale" = w_median, method = list) %>%
tab_pivot(stat_position = "inside_rows")  %>% 
compute(
     "Median Subscale" = as.character(round( `Median Subscale`))
)
```

**Comment by blam3** [comment]
It works! Thanks for your help!

**Comment by zelihay** [comment]
Hi Mr. Demin,

The codes work very well, but I couldn't see the same result in the Excel file. I think it is about the openxlsx package. I've tried to add style (`style = createStyle(numFmt = "0")`) to overcome the problem, but it gives the numbers with one digit in any case.
```

col1=A %>%
  tab_prepend_all %>%
  tab_cols(Index1) %>%
  tab_cells(mrset(S1,T2BS1)) %>% 
  tab_stat_cases(total_row_position = "none") %>%
  tab_cells(S1) %>% 
  tab_stat_fun("Mean" = w_mean) %>%
  tab_stat_unweighted_valid_n(label = "Total") %>%
  
  tab_pivot()%>%
  tab_format_digits(zero_digits_labels = !perl("Mean"))


wb = createWorkbook()
sh1 = addWorksheet(wb, "Count")

xl_write(col1, wb, sh1,
         # remove '#' sign from totals
         col_symbols_to_remove = "#",
         row_symbols_to_remove = "#",
         # format total column as bold
         other_col_labels_formats = list("#" = createStyle(textDecoration = "bold")),
         other_cols_formats = list("#" = createStyle(textDecoration = "bold"))
)

saveWorkbook(wb, "file.xlsx", overwrite = TRUE)

```

Do you know how to solve this problem?

Many thanks

**Comment by gdemin** [comment]
Hi, @zelihay 
 
This should work: 
```R
xl_write(col1, wb, sh1,
         # remove '#' sign from totals
         col_symbols_to_remove = "#",
         row_symbols_to_remove = "#",
         # format total column as bold
         other_col_labels_formats = list("#" = createStyle(textDecoration = "bold")),
         other_cols_formats = list("#" = createStyle(textDecoration = "bold")),
         main_format = openxlsx::createStyle(halign = "right", numFmt = format(0, nsmall = 0)),
         other_rows_formats = list("Mean" = openxlsx::createStyle(halign = "right", numFmt = format(0, nsmall = 1)))
)

```

**Comment by zelihay** [comment]
Thanks a lot! That works :)

**Comment by JhalokTalukdar** [comment]
Hi @gdemin 

Thank you for the above solutions regarding decimal places.  I am trying to get different decimal places for different rows and columns. For example, I want a complete number for Unv. valid N, 2 decimal places for "#Total" variable but 3 decimal places for "Sex" and "Age" variables
![image](https://user-images.githubusercontent.com/13270859/235948252-90fa875d-f8c8-4449-90c7-2afc1e464a9f.png)
. Could you please help how can I do that? Thank you so much for your help. 

options(scipen=999)
expss_digits(digits = 3)
dat %>% 
    tab_cells(PhysicalFrailty, PsychologicalFrailty, SocialFrailty) %>%
    tab_cols(total(), Sex, Age) %>% 
    tab_stat_mean_sd_n() %>%
    tab_pivot() %>% 
    set_caption("Table with summary statistics and significance marks.") %>% 
compute(
     "Unw. valid N" = as.character(round( `Unw. valid N`))
)

**Comment by gdemin** [comment]
@JhalokTalukdar 

You can use the following code:
```
library(expss)

#' @param tbl table, result of cro_*, tab_*
#' @param special_digits_labels function/value which return TRUE on row labels for which we want special-digits formatting
#' @param special_digits integer number of digits after decimal separator for special rows
#' @param digits integer number of digits after decimal separator
tab_format_digits = function(tbl, 
                             special_digits_labels = fixed("#"), 
                             special_digits = 0,
                             digits = get_expss_digits()
){
    special_digits_rows = tbl[[1]] %has% special_digits_labels
    for(i in seq_along(tbl)[-1]){
        tbl[[i]] = ifelse(special_digits_rows, 
                          formatC(tbl[[i]], format = "f", digits = special_digits),
                          formatC(tbl[[i]], format = "f", digits = digits)
        )
    }
    tbl
}

options(scipen=999)
expss_digits(digits = 3)
mtcars %>%
    tab_cells(cyl, gear) %>%
    tab_cols(total(), am, vs) %>%
    tab_stat_mean_sd_n() %>%
    tab_pivot() %>%
    set_caption("Table with summary statistics and significance marks.") %>%
    tab_format_digits(
        special_digits_labels = fixed("Unw. valid N"),
        special_digits = 2
    )

```

**Comment by JhalokTalukdar** [comment]
Hi @gdemin,

Thank you for getting back to me so quickly. I ran the codes you gave me but I didn't get the expected results (screenshot attached). Did I miss anything? 

![image](https://user-images.githubusercontent.com/13270859/236647982-05a65b25-e14a-4cd1-893b-d103950bc852.png)

**Comment by gdemin** [comment]
@JhalokTalukdar 
I have the desired output both in the console, in the viewer and after knitting:
![image](https://user-images.githubusercontent.com/3617375/236648759-6a63391c-8677-4fd9-ac4c-4181664dc241.png)
![image](https://user-images.githubusercontent.com/3617375/236648770-d01fbcfc-2567-4690-8474-a1a094abfc97.png)
![image](https://user-images.githubusercontent.com/3617375/236648839-4bed8a55-58c2-417f-a741-e0c94d52e123.png)

**Comment by JhalokTalukdar** [comment]
Hi @gdemin,

Thank you so much. It is working in my console now. I highly appreciate you help.
