### ISSUE TITLE
Exporting tables into Excel

### ISSUE THREAD

**Issue by zelihay** [gdemin/expss#23]
Hi Mr. Gregory,
I have R version 3.5.1, and I've successfully installed the openxlsx package. When I try to rerun the same codes in the guide (https://cran.r-project.org/web/packages/expss/vignettes/xlsx-export.html), I get this error;
> xl_write(mtcars_table, wb, sh)
**Error in openxlsx::createStyle(borderStyle = borders$borderStyle, borderColour = borders$borderColour,  : 
  Unknown border argument**

How can I solve this problem?
Thank you for your help.

All my best,
Zeliha

**Comment by gdemin** [comment]
Hi, Zelihay,
Sorry, I can't reproduce this issue. Could you run the following code in clean session? Will it give the same error?
```R
library(expss)
library(openxlsx)
data(mtcars)
mtcars = apply_labels(mtcars,
                      mpg = "Miles/(US) gallon",
                      cyl = "Number of cylinders",
                      disp = "Displacement (cu.in.)",
                      hp = "Gross horsepower",
                      drat = "Rear axle ratio",
                      wt = "Weight (lb/1000)",
                      qsec = "1/4 mile time",
                      vs = "Engine",
                      vs = c("V-engine" = 0,
                             "Straight engine" = 1),
                      am = "Transmission",
                      am = c("Automatic" = 0,
                             "Manual"=1),
                      gear = "Number of forward gears",
                      carb = "Number of carburetors"
)

mtcars_table = mtcars %>% 
    calc_cro_cpct(
        cell_vars = list(cyl, gear),
        col_vars = list(total(), am, vs)
    ) %>% 
    set_caption("Table 1")

wb = createWorkbook()
sh = addWorksheet(wb, "Tables")
xl_write(mtcars_table, wb, sh)
saveWorkbook(wb, "table1.xlsx", overwrite = TRUE)
```

**Comment by zelihay** [comment]
Hi Mr. Gregory,
I did what you've said. Although I get the same error, I notice that I also get the Excel file in the Files. You can find the screenshot. Should I ignore the error and continue with it?
Thank you for your reply.

![exportingexcel](https://user-images.githubusercontent.com/35660557/50633275-d0bd0580-0f5b-11e9-86c2-3f3e56209028.jpeg)

**Comment by gdemin** [comment]
As usual, could you provide results of `sessionInfo()`?

**Comment by zelihay** [comment]
Here are the results: 
![sessioninfo](https://user-images.githubusercontent.com/35660557/50633963-1e3a7200-0f5e-11e9-8508-3c36665b01ab.jpeg)

**Comment by zelihay** [comment]
I wrote these codes one by one, and I got an error for the last one.

 openxlsx::createStyle(
     borderStyle = "thin",
     borderColour = "black",
     border = "right"
)
**Error in openxlsx::createStyle(borderStyle = "thin", borderColour = "black",  : 
  Unknown border argument**

**Comment by gdemin** [comment]
Hmm, it seems it is bug in the openxlsx package. Please, execute the code below and post output here:
```R
toupper("right")
Sys.setlocale(locale = "C")
toupper("right")
openxlsx::createStyle(
    borderStyle = "thin",
    borderColour = "black",
    border = "right"
)
```

**Comment by zelihay** [comment]
toupper("right")

[1] "RİGHT"

Sys.setlocale(locale = "C")

[1] "LC_CTYPE=C;LC_NUMERIC=C;LC_TIME=C;LC_COLLATE=C;LC_MONETARY=C;LC_MESSAGES=tr_TR.UTF-8;LC_PAPER=tr_TR.UTF-8;LC_NAME=C;LC_ADDRESS=C;LC_TELEPHONE=C;LC_MEASUREMENT=tr_TR.UTF-8;LC_IDENTIFICATION=C"

toupper("right")

[1] "RIGHT"

openxlsx::createStyle(
     borderStyle = "thin",
     borderColour = "black",
     border = "right"
 )

A custom cell style. 

 Cell formatting: GENERAL 
 Cell borders: Right: thin 
 Cell border colours: #000000 
 
Sys.setlocale(locale = "tr_TR.UTF-8")

[1] "LC_CTYPE=tr_TR.UTF-8;LC_NUMERIC=C;LC_TIME=tr_TR.UTF-8;LC_COLLATE=tr_TR.UTF-8;LC_MONETARY=tr_TR.UTF-8;LC_MESSAGES=tr_TR.UTF-8;LC_PAPER=tr_TR.UTF-8;LC_NAME=C;LC_ADDRESS=C;LC_TELEPHONE=C;LC_MEASUREMENT=tr_TR.UTF-8;LC_IDENTIFICATION=C"

**Comment by gdemin** [comment]
Thank you very much for your patience:)
It is a bug in openxlsx package - it has conflict with Turkish locale. I will report this issue to the package author. 
By now you can try to export by setting locale before the export with `Sys.setlocale(locale = "C")` and setting it back with `Sys.setlocale(locale = "tr_TR.UTF-8")` after the export:
```R
Sys.setlocale(locale = "C")
xl_write(mtcars_table, wb, sh)
Sys.setlocale(locale = "tr_TR.UTF-8")
```
Not very good workaround but it is better than nothing.

**Comment by zelihay** [comment]
Thank you so much for your help :)
