### ISSUE TITLE
Set options htmlTable

### ISSUE THREAD

**Issue by robertogilsaura** [gdemin/expss#30]
Hi @gdemin 

Can I set htmlTable options for all the expss crosstabs? I want to print all the tables (tab) in output with this options (simple example):

`
htmlTable(tab,
    css.cell = c('min-width: 33%; border-top: 1px solid #f0f0f0;font-family: Roboto', rep('min-width: 50px; border-top: 1px solid #f0f0f0;', ncol(tab) - 1)),
    align = paste(rep('c', ncol(tab) - 1), collapse = ''),
    align.header =  paste(rep('c',ncol(tab)),collapse = ''),
    align.cgroup =  paste(rep('c',ncol(tab)),collapse = ''),
    col.rgroup = c('#eeeeee', '#ffffff'),
    col.columns = c('#f8f8f8', '#f0f0f0'),
    css.rgroup = 'font-weight: 900;font-size: 1em',
    css.rgroup.sep = 'hr style="border-color: #333333;',
    css.cgroup = 'font-weight: 900;font-size: 1em',
    css.cgroup.sep = 'hr style="border-color: #333333;'
)
`

Thanks in advance.
Rober

**Comment by gdemin** [comment]
Simples way is to create your own functions and use it instead of original htmlTable2. It can be looks like part of the chain:
```R
htmlTable2 = . %>% htmlTable(css.cell = c('min-width: 33%; border-top: 1px solid #f0f0f0;font-family: Roboto', rep('min-width: 50px; border-top: 1px solid #f0f0f0;', ncol(tab) - 1)), align = paste(rep('c', ncol(tab) - 1), collapse = ''), align.header = paste(rep('c',ncol(tab)),collapse = ''), align.cgroup = paste(rep('c',ncol(tab)),collapse = ''), col.rgroup = c('#eeeeee', '#ffffff'), col.columns = c('#f8f8f8', '#f0f0f0'), css.rgroup = 'font-weight: 900;font-size: 1em', css.rgroup.sep = 'hr style="border-color: #333333;', css.cgroup = 'font-weight: 900;font-size: 1em', css.cgroup.sep = 'hr style="border-color: #333333;' )
```

**Comment by robertogilsaura** [comment]
Yes, Thanks a lot. It's easier than I think it.

Rober
