### ISSUE TITLE
table size issues

### ISSUE THREAD

**Issue by ehsong** [gdemin/expss#32]
Hi, I am trying to use the expss package but I can't seem to adjust the table size. I tried your first example but my table looks likes this:

<img width="589" alt="_var_folders_d5_3zwq438d2mn5d_92hlxqzcg00000gn_t__rtmpjxot8l_preview-47046616b336_html" src="https://user-images.githubusercontent.com/5554659/53789709-f1f98e00-3ed9-11e9-8f07-0083b1d2fdf9.png">

How can I make this table smaller? I'm using rmarkdown, and my setup is:

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = TRUE)
```

**Comment by gdemin** [comment]
expss use htmlTable package for table rendering. And there is `css.cel` argument which can be used for padding adjustment:
```R
library(expss)
data(mtcars)
mtcars = apply_labels(mtcars,
                      mpg = "Miles/(US) gallon",
                      cyl = "Number of cylinders",
                      disp = "Displacement (cu.in.)",
                      hp = "Gross horsepower",
                      drat = "Rear axle ratio",
                      wt = "Weight (1000 lbs)",
                      qsec = "1/4 mile time",
                      vs = "Engine",
                      vs = c("V-engine" = 0,
                             "Straight engine" = 1),
                      am = "Transmission",
                      am = c("Automatic" = 0,
                             "Manual"=1),
                      gear = "Number of forward gears",
                      carb = "Number of carburetors"
)


cro(mtcars$am, mtcars$vs) %>% 
    htmlTable(css.cell = "padding: 0px;")
```

**Comment by ehsong** [comment]
Hi, thank you -- but I'm still having trouble decreasing the table size. Padding changes the margins along the text within the cell, but doesn't seem to decrease the cell size nor the table size. I also tried `<style type="text/css">` in the front of the document and changed the font size, but it won't decrease the table size.

**Comment by gdemin** [comment]
Соuld you provide screenshot of the entire document? Does it look siginificantly different from the introductionary vignette?

**Comment by ehsong** [comment]
My file is [https://www.dropbox.com/s/46gm291vkkl9hnc/Untitled.md?dl=0](here)

**Comment by ehsong** [comment]
Hi, I figured it out! It had to do with markdown format. The markdown format should be output: html_document, not githubdocument

**Comment by gdemin** [comment]
I open your document and last table (table with zero) padding looks ok for me:
![default](https://user-images.githubusercontent.com/3617375/53833752-5845e580-3f9a-11e9-8220-1d9542dae870.png)
