### ISSUE TITLE
tab_sort_desc

### ISSUE THREAD

**Issue by zelihay** [gdemin/expss#34]
Hi Mr. Demin,

I am happily using your package so far, thanks again.
I've tried to use "tab_sort_desc()" function and it is very well working with "tab_stat_cases" and "tab_stat_cpct", but not with significant tests.

I am using the below code for the test;

"  tab_last_sig_cpct(sig_level = 0.05, delta_cpct = 0,
                    min_base = 30, sig_labels = LETTERS, bonferroni = TRUE) %>% "

Do you think is there any issue here?

Thanks for your help
Regards,
Zeliha

**Comment by gdemin** [comment]
After significance testing table columns are converted from numeric to character. That's why sorting with significance tests is not good. However you can try to sort before significance testing:
```
%>% tab_sort_desc() %>%
 tab_last_sig_cpct(sig_level = 0.05, delta_cpct = 0,
min_base = 30, sig_labels = LETTERS, bonferroni = TRUE) %>%
```

**Comment by zelihay** [comment]
Great! Thanks for the fast response!
