### ISSUE TITLE
tab_subgroup() with mrset()

### ISSUE THREAD

**Issue by robertogilsaura** [gdemin/expss#35]
Hi @gdemin ...Thats is question, not an issue. 

Can I fix a criteria with tab_subgroup() like this?

```
df <- data.frame(id=seq(1:10),VAR_1=sample(1:5,10,replace=TRUE), VAR_2=sample(1:5,10,replace=TRUE))
df %>% 
    tab_subgroup(mrset(VAR_1 %to% VAR_2)==1) %>% 
    tab_cols(total()) %>% 
    tab_cells(id) %>% 
    tab_stat_cases() %>% 
    tab_pivot()
```
This table select records with VAR_1==1 but not records with VAR_2==1

The only correct way for writing this subgroup would be VAR_1==1 | VAR_2==1?

Thanks in advance.

**Comment by gdemin** [comment]
Hi,  you need `%has%`: 
```
tab_subgroup(mrset(VAR_1 %to% VAR_2) %has% 1) 
```

**Comment by robertogilsaura** [comment]
Great !!!

Thanks.
