### ISSUE TITLE
TESTS: Errors with develop matrixStats 0.54.0-9000

### ISSUE THREAD

**Issue by HenrikBengtsson** [gdemin/expss#36]
Hi. While fixing https://github.com/HenrikBengtsson/matrixStats/issues/140 that you posted, I've updated:

> Version: 0.54.0-9000 [2019-08-13]
> 
> SIGNIFICANT CHANGES:
> 
>  * weightedVar(), weightedSd(), weightedMad(), and their row- and column-
>    specific counter parts now return a missing value if there are missing
>    values in any of the weights 'w' after possibly dropping (x, w) elements
>    with missing values in 'x' (na.rm = TRUE).  Previously, na.rm=TRUE would
>    also drop (x, w) elements where 'w' was missing.  With this change, we
>    now have that for all functions in this package, na.rm=TRUE never applies
>    to weights - only 'x' values.

This affects your [expss tests on this](https://github.com/gdemin/expss/blob/master/tests/testthat/test_weighted_stats.R), which now produce three errors:
```r
 ERROR
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  
  ── 3. Failure: (unknown) (@test_weighted_stats.R#169)  ───────────────
  w_mad(x, w, na.rm = FALSE) not equal to matrixStats::weightedMad(...).
  1/1 mismatches
  [1] 0.193 - NA == NA
  
  Set default dataset to 'd_iris'
  ══ testthat results  ═════════════════════════════════════════════════
  [ OK: 1991 | SKIPPED: 0 | WARNINGS: 0 | FAILED: 3 ]
  1. Failure: (unknown) (@test_weighted_stats.R#77) 
  2. Failure: (unknown) (@test_weighted_stats.R#92) 
  3. Failure: (unknown) (@test_weighted_stats.R#169) 
  
  Error: testthat unit tests failed
  Execution halted
```

In all these cases, `matrixStats::weighted{Var,Mad}(x, w)`, return `NA` because there's non-dropped `(x,w)` element for which `w` is a missing value.

Could you please fix/workaround this in your tests because it's currently a show stopper for submitting the next version of matrixStats to CRAN. Thxs.

**Comment by gdemin** [comment]
Hi,
I will release update with fix on next week.

**Comment by gdemin** [comment]
Updated version is on CRAN now.
