### ISSUE TITLE
Compare all columns

### ISSUE THREAD

**Issue by zelihay** [gdemin/expss#37]
Hi Mr. Demin,

I have a nested table and I need to put significant tests for all columns.

The default mode for compare_type is "subtable". Is it possible to change that mode to compare all columns?

I used these functions:

For table columns:  tab_cols(Quest1 %nest% list(total(), Quest2)) %>%

For significant tests:   tab_last_sig_cpct(sig_level = 0.05, delta_cpct = 0,
                    min_base = 30, sig_labels = LETTERS, 
                    keep = "percent",bonferroni = TRUE) %>% 

Thanks for your help.

All my best,
Zeliha

**Comment by gdemin** [comment]
Hi, Zelihay,
There is no such option now but you can to change "|" in the table column names to something else and then mark significance.
Significance test uses "|" to find table blocks so without this separator  it will compare all columns.
It will looks like this:
```R
%>% setNames(., gsub("|", "-", colnames(.), fixed = TRUE)) %>% 
 tab_last_sig_cpct(sig_level = 0.05, delta_cpct = 0, min_base = 30, sig_labels = LETTERS,
        keep = "percent",bonferroni = TRUE) %>% 
    setNames(., gsub("-", "|", colnames(.), fixed = TRUE))
```
