### ISSUE TITLE
Error in executing Rmd

### ISSUE THREAD

**Issue by robertogilsaura** [gdemin/expss#39]
Hi @gdemin, 
I've a problem with a chunk  in *.rmd file. The instruction set doesn't run properly in a complete *.rmd, but it runs properly in an isolate *.rmd. The instruction set runs properly in a standard script, too. The piece of code is this ...

_Note: loading data and package is repeated in the instrucion set for academic needs_

```{r Pregunta8.}
suppressMessages(library(expss, quietly = TRUE))
data <- read_spss("~/_datos/99.tmim/testapp.sav")
data$RLOADING = recode(data$LOADING, "Bajo" = 0.00 %thru% 25.00 ~ 1, "Medio" = 25.01 %thru% 46.00 ~ 2, "Alto" = 46.01 %thru% 100 ~ 3)
data$RSPEED = recode(data$SPEED, "Bajo" = 0.00 %thru% 29.80 ~ 1, "Medio" = 29.81 %thru% 50.00 ~ 2, "Alto" = 50.01 %thru% 100 ~ 3)
data$RSECURITY = recode(data$SECURITY, "Bajo" = 0.00 %thru% 25.00 ~ 1, "Medio" = 25.01 %thru% 34.20 ~ 2, "Alto" = 34.21 %thru% 100 ~ 3)
data$RPRIVACY = recode(data$PRIVACY, "Bajo" = 0.00 %thru% 39.00 ~ 1, "Medio" = 39.01 %thru% 53.20 ~ 2, "Alto" = 53.21 %thru% 100 ~ 3)
data$RDESIGN = recode(data$DESIGN, "Bajo" = 0.00 %thru% 41.00 ~ 1, "Medio" = 41.01 %thru% 54.00 ~ 2, "Alto" = 54.01 %thru% 100 ~ 3)
options(digits = 3, width = 9999)
data %>% 
     tab_cols(total(), AGENCY) %>% 
     tab_cells(RLOADING, RSPEED, RSECURITY, RPRIVACY, RDESIGN) %>% 
     tab_stat_cpct() %>% 
     tab_last_sig_cases() %>% 
     tab_pivot()
data %>% 
     tab_cols(total(), AGENCY) %>% 
     tab_cells(RLOADING, RSPEED, RSECURITY, RPRIVACY, RDESIGN) %>% 
     tab_stat_cpct() %>% 
     tab_last_sig_cell_chisq() %>%
     tab_pivot()
```
and the stop error is ...

_Quitting from lines 163-183 (caso1.inf.solucion.Rmd) 
Error in if (length(ans) == 0L || as.character(ans[[1L]])[1L] == "~") { : 
  valor ausente donde TRUE/FALSE es necesario
Calls: <Anonymous> ... eval -> eval -> recode -> recode.numeric -> [ -> [.formula
Ejecución interrumpida_

I send a zip file with complete and isolate rmd files and *.sav file. I would greatly appreciate your help, as this fact leaves me very baffled. 

Thanks in advance...

[rstudio-export.zip](https://github.com/gdemin/expss/files/3721612/rstudio-export.zip)

**Comment by gdemin** [comment]
Hi @robertogilsaura,

You load `dplyr` after the `expss` and `recode` which you try to call is from `dplyr`. You need to load `expss` last or explicitly specify package, e. g.  `expss::recode` or `dplyr::recode`.

P. S. Second `library` with the same package doesn't count:
```R
library(expss)
library(dplyr) # dplyr 'recode' take precedence over expss 'recode'
library(expss) # doesn't change anything
```
[caso1.inf.solucion.Rmd.zip](https://github.com/gdemin/expss/files/3722030/caso1.inf.solucion.Rmd.zip)

**Comment by robertogilsaura** [comment]
A lot of thanks @gdemin . The instruction set runs properly with this change. I have read about sequence in doc, but I didn`t match cause-effect.

A lot of thanks, as always ... and on Sunday!
