### ISSUE TITLE
DT 0.3

### ISSUE THREAD

**Issue by yihui** [gdemin/expss#4]
Hi, I'm preparing a new release of DT, and I found some tests in your package failed with the dev version of DT:
https://github.com/gdemin/expss/blob/master/tests/testthat/test_html_datatable.R

I'm not sure what exactly you were trying to do in these tests, so I'll appreciate it if you could install the dev version of DT, and see if it is straightforward to fix these tests, or tell me what I need to do in DT to prevent the `R CMD check` breakage your package.

```r
devtools::install_github('rstudio/DT')
```

```
checking tests ... ERROR
  Running ‘testthat.R’ [75s/118s]
Running the tests in ‘tests/testthat.R’ failed.
Complete output:
  > library(testthat)
  > library(expss)
  > options(width = 1000)
  > options(covr = TRUE)
  > test_check("expss")
  Set default dataset to 'a'
... 205 lines ...
  3. Failure: (unknown) (@test_html_datatable.R#55) 
  4. Failure: (unknown) (@test_html_datatable.R#58) 
  5. Failure: (unknown) (@test_html_datatable.R#61) 
  6. Failure: (unknown) (@test_html_datatable.R#64) 
  7. Failure: (unknown) (@test_html_datatable.R#67) 
  8. Failure: (unknown) (@test_html_datatable.R#71) 
  9. Failure: (unknown) (@test_html_datatable.R#75) 
  1. ...
  
  Error: testthat unit tests failed
  Execution halted
```

Thanks!

**Comment by gdemin** [comment]
Thanks, fixed.

**Comment by yihui** [comment]
Thanks for the quick fix! As I said, I wasn't sure what you were trying to test, but if you were testing the data structure of the returned value of `datatable()`, that would make me feel nervous, because I cannot guarantee it will never change. I'd appreciate it if you could either avoid testing to this level of granularity, or `skip_on_cran()` for such tests so that only you know certain things have been changed without bothering CRAN. My blood pressure raises every time I submit a new version of any of my packages to CRAN, and unfortunately I maintain many packages on CRAN...

**Comment by gdemin** [comment]
I try to test that object of class 'etable' in my package are rendered correctly with 'datatable'. Ok, I added `skip_on_cran` for these tests.

**Comment by yihui** [comment]
Sounds perfect. Thank you very much!
