### ISSUE TITLE
Error to re-run code from examples

### ISSUE THREAD

**Issue by nsahr** [gdemin/expss#40]
Getting the following error:

Error in setalloccol(ans): could not find function "setalloccol"
Traceback:

1. mtcars %>% calc_cro_cpct(cyl, list(total(), am %nest% vs))
2. withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
3. eval(quote(`_fseq`(`_lhs`)), env, env)
4. eval(quote(`_fseq`(`_lhs`)), env, env)
5. `_fseq`(`_lhs`)
6. freduce(value, `_function_list`)
7. withVisible(function_list[[k]](value))
8. function_list[[k]](value)
9. calc_cro_cpct(., cyl, list(total(), am %nest% vs))
10. calculate_internal(data, expr = expr, parent = parent.frame())
11. eval(expr, envir = e, enclos = baseenv())
12. eval(expr, envir = e, enclos = baseenv())
13. cro_cpct(cell_vars = cyl, col_vars = list(total(), am %nest% 
  .     vs), row_vars = NULL, weight = NULL, subgroup = NULL, total_label = NULL, 
  .     total_statistic = "u_cases", total_row_position = c("below", 
  .         "above", "none"))
14. multi_cro(cell_vars = cell_vars, col_vars = col_vars, row_vars = row_vars, 
  .     weight = weight, subgroup = subgroup, total_label = total_label, 
  .     total_statistic = total_statistic, total_row_position = total_row_position, 
  .     stat_type = "cpct")
15. lapply(row_vars, function(each_row_var) {
  .     res = lapply(cell_vars, function(each_cell_var) {
  .         all_col_vars = lapply(col_vars, function(each_col_var) {
  .             elementary_cro(cell_var = each_cell_var, col_var = each_col_var, 
  .                 row_var = each_row_var, weight = weight, subgroup = subgroup, 
  .                 total_label = total_label, total_statistic = total_statistic, 
  .                 total_row_position = total_row_position, stat_type = stat_type)
  .         })
  .         Reduce(merge, all_col_vars)
  .     })
  .     res = do.call(add_rows, res)
  . })
16. FUN(X[[i]], ...)
17. lapply(cell_vars, function(each_cell_var) {
  .     all_col_vars = lapply(col_vars, function(each_col_var) {
  .         elementary_cro(cell_var = each_cell_var, col_var = each_col_var, 
  .             row_var = each_row_var, weight = weight, subgroup = subgroup, 
  .             total_label = total_label, total_statistic = total_statistic, 
  .             total_row_position = total_row_position, stat_type = stat_type)
  .     })
  .     Reduce(merge, all_col_vars)
  . })
18. FUN(X[[i]], ...)
19. lapply(col_vars, function(each_col_var) {
  .     elementary_cro(cell_var = each_cell_var, col_var = each_col_var, 
  .         row_var = each_row_var, weight = weight, subgroup = subgroup, 
  .         total_label = total_label, total_statistic = total_statistic, 
  .         total_row_position = total_row_position, stat_type = stat_type)
  . })
20. FUN(X[[i]], ...)
21. elementary_cro(cell_var = each_cell_var, col_var = each_col_var, 
  .     row_var = each_row_var, weight = weight, subgroup = subgroup, 
  .     total_label = total_label, total_statistic = total_statistic, 
  .     total_row_position = total_row_position, stat_type = stat_type)
22. make_datatable_for_cro(cell_var = cell_var, col_var = col_var, 
  .     row_var = row_var, weight = weight, subgroup = subgroup)
23. data.table(cell_var, col_var)

**Comment by wck01** [comment]
I guess this error due to latest data.table package. In the past, we can define data.table(x) as data.table object. In the latest version, we need to use as.data.table(x). I think we need to wait for the developer update. Alternative, you need to downgrade the data.table version.

**Comment by sjewo** [comment]
I changed just one line and it seems to work: 18b1717 
Until this issue is fixed you can you the fork in my repo:
```
library(devtools)
install_github("sjewo/expss")
```

**Comment by gdemin** [comment]
Hi, @nsahr,

This is mysterious bug due to the latest data.table update.  I don't know why it happens (any ideas?) but it can be easily fixed without changing any line of code. Just reinstall 'expss' with dependencies:

```R
 install.packages ("expss", dependencies = TRUE)
```

@wck01 As far as I know in the latest data.table version nothing changes about `data.table` vs `as.data.table`.
@sjewo Your solution works because you reinstall `expss` after making changes.

**Comment by gdemin** [comment]
See #42
