### ISSUE TITLE
Add as_hux function for etables

### ISSUE THREAD

**Issue by sjewo** [gdemin/expss#41]
Hi Greogory,

I like your package very much, but I'm miss a function to export the tables to word or latex.

I made a working, but not complete example, for a function to convert `etables` to `huxtable` objects (for the huxtable package by @hughjonesd): sjewo/huxtable@6079014

The function will merge cells automatically and returns a `huxtable` object for export to Word or LaTeX. @hughjonesd suggested (hughjonesd/huxtable#117) to include this function rather into `expss`  than into `huxtable`.

What do you think?

**Comment by gdemin** [comment]
Ok, I will add as_hux in the next `expss` release.

Does your `as_hux.etable` implemention  support nested header and rowlabels?

**Comment by sjewo** [comment]
Great! 

The function will convert nested headers and rowlabels. Here is a working example:

```
data(mtcars)

mtcars = modify(mtcars,{
    var_lab(vs) = "Engine"
    val_lab(vs) = c("V-engine" = 0, 
                    "Straight engine" = 1) 
    var_lab(am) = "Transmission"
    val_lab(am) = c(automatic = 0, 
                    manual=1)
})

# stacked frequencies
cars <- fre(list(mtcars$vs, mtcars$am))

library(huxtable)

#' @export
#' @rdname as_huxtable
# FIXME: Merge cells hierarchically
# FIXME: Merge "Total Cases"
# TODO: More testing
as_huxtable.etable  <- function(x, ...) {

  # start with default huxtable
  ht <- huxtable:::as_huxtable.default(x)

  # Split row_lables of merged cells
  rown <- do.call("rbind", strsplit(ht[[1]], "\\|"))

  # Delete old row_labels
  ht[,1] <- NULL 

  # Atttach splitted row_labels
  ht <- cbind(rown, ht)

  # Iterate over columns
  for(j in seq_len(ncol(rown))) {
    # Add new labels and merge cells
    rownlab <- unique(rown[,j])
    for(r in rownlab) {
      mergel <- which(rown[, j] == r)
      # If alternating labels exist, do nothing
      if(isTRUE(all.equal(min(mergel):max(mergel), mergel))) {
        ht <- merge_cells(ht, mergel, j)
      }
    }
  }

  # Split column labels of merged cells
  coln <- t(do.call("rbind", strsplit(names(ht), "\\|")))

  # Remove default data.frame names (V1, V2, ...)
  coln[coln %in% paste0("V", seq_len(ncol(ht)))] <- ""

  # Attach splitted column names
  ht <- rbind(coln, ht)
  # Iterate over rows
  for(j in seq_len(nrow(coln))) {
    # Add new labels and merge cells
    colnlab <- unique(coln[j, ])
    for(r in colnlab) {
      mergel <- which(coln[j, ] == r)
      # If alternating labels exist, do nothing
      if(isTRUE(all.equal(min(mergel):max(mergel), mergel))) {
        ht <- merge_cells(ht, j, mergel)
      }
    }
  }

  return(ht)
}

cars_ht <- as_huxtable.etable(cars)

cars_ht <- set_all_borders(cars_ht, value = T)
cars_ht <- set_all_border_colors(cars_ht, "black")
cars_ht <- set_all_border_styles(cars_ht, "solid")
quick_html(cars_ht)
```

Before a release I have to do some additional work to make this more reliable and also do some more testing.

**Comment by gdemin** [comment]
I tried it - really nice output!

>  ... do some more testing

You can use test cases from htmlTable.etable tests: https://github.com/gdemin/expss/blob/master/tests/testthat/test_htmlTable.R
It will be very nice if your code gives sensible result for the edge cases like empty colnames, rownames, and etc.

**Comment by sjewo** [comment]
I'll adopt the test tables and probably write additional test for this function.

I added a new branch huxtable in my forked repo and will make a pull request once I have finished the testing.

**Comment by sjewo** [comment]
I did some testing (using the test cases from htmlTable.etable) and tweaked the code for some edge cases. Up to now I'm happy with the results of the conversion.

```
  devtools::install_github("sjewo/expss@huxtable")

  library(huxtable)
  library(expss)
  
  data(mtcars)
  mtcars = apply_labels(mtcars,
                        mpg = "Miles/(US) gallon|Mean",
                        cyl = "Number of cylinders",
                        disp = "Displacement (cu.in.)|Mean",
                        hp = "Gross horsepower|Mean",
                        drat = "Rear axle ratio",
                        wt = "Weight (lb/1000)",
                        qsec = "1/4 mile time|Mean",
                        vs = "Engine",
                        vs = c("V-engine" = 0,
                               "Straight engine" = 1),
                        am = "Transmission",
                        am = c("Automatic" = 0,
                               "Manual"=1),
                        gear = "Number of forward gears",
                        carb = "Number of carburetors"
  )
  
  options(expss.digits = NA)
  mtcars_table = cro_cpct(list(mtcars$vs %nest% mtcars$am), 
                          list(mtcars$vs %nest% mtcars$am, "#Total")) 

  cars_ht <- as_huxtable(mtcars_table)

  cars_ht <- set_all_borders(cars_ht, value = T)
  cars_ht <- set_all_border_colors(cars_ht, "black")
  cars_ht <- set_all_border_styles(cars_ht, "solid")
  
  quick_html(cars_ht)
```

While testing I experienced some problems with masked function from huxtable (e.g. `set_caption`). Same problem the other way with `as_hux()`. The last one could be easily solved by renaming `as_hux` in `expss`, but `caption` and `add_columns` will still be masked.

@gdemin  @hughjonesd : Any ideas how to share methods for different classes between packages?

**Comment by hughjonesd** [comment]
If it's within your own code, just qualify method calls as
huxtable::caption() or expss::caption().

**Comment by sjewo** [comment]
Using the different function in the package is not a big deal. It may be a problem for a regular user if their code stops working because of a masked `set_caption` function. At the moment the functions will only work for either `etable` or `huxtable` objects.

**Comment by gdemin** [comment]
@sjewo Really impressive work!

There are four conflicting functions: `add_columns`, `add_rows`, `set_caption`, `where`.
I will easily fix `set_caption` to avoid conflicts because in the `huxtable` it relies on generic function `caption`.
 `add_columns` and `add_rows` in the expss are generics and used only for data.frame/etable so I can add methods for huxtable. However it will fix conflicts only partially because in the huxtable these functions also act on data.frames.
`where`  has different meaning in each package - I don't know how to make something sensible here.
So I think its better to fix set_caption and keep other functions as is.
`huxtable` will be in the suggested packages so user can load packages in the order of his/her preferences.

**Comment by sjewo** [comment]
@gdemin thank you!

I think your suggestions will work out! I already added some methods for `set_caption`, but I did not know if you where willing to add method for the `huxtable` class.  I think from a user perspective your plan looks best!

Whats next? Should I do a pull request?

**Comment by gdemin** [comment]
@sjewo Yes, make pull request as you finish.

**Comment by gdemin** [comment]
@sjewo 
I am going to release new version next week. It will be very nice if I include your work on `as.hux` in this release. Could I expect the pull request in the nearest time?

**Comment by sjewo** [comment]
@gdemin 
I created a pull request a view minutes ago. Beside of the conflicts in generic functions it seems to work very well.

**Comment by sjewo** [comment]
@gdemin 
My students did test the new functions in the last days and run often into trouble because of the duplicated functions in expss and huxtable, especially if huxtable is loaded after expss. Then the as_hux function will be overwritten by the default function from huxtable. It might be sensible to rename also the as_hux function to a non conflicting name like to_hux.

**Comment by gdemin** [comment]
@sjewo Thanks, I will make something about it.

**Comment by gdemin** [comment]
@sjewo I fixed most conflicts with huxtable - `as_huxtable`, `set_caption` and `caption` should work without any problems. There was no need to define `as_huxtable` function. Only methods are needed. 
Also, for future reference, calls to internal functions of other packages (e. g. `knitr:::to_pandoc`) is not allowed on CRAN.   
I think the package is ready for submitting. You can install it for testing from 'develop' branch. If all is ok, I will upload it tomorrow evening.

**Comment by sjewo** [comment]
@gdemin Thank you for fixing this issues! I run into problems without defining a function - great you figured it out!

I did some tests with different scripts, tables, knitr documents and everything seems to work.

From my point of view the package is ready for upload to CRAN.

**Comment by gdemin** [comment]
Ok, so it is nothing to wait:) expss on its way to CRAN.  Thank you for your contribution.

**Comment by hughjonesd** [comment]
Good work guys! :-)
