### ISSUE TITLE
cro_rpct reports column cases  instead of row cases

### ISSUE THREAD

**Issue by sjewo** [gdemin/expss#44]
Hi Gregory,

I wanted to create a crosstable with row percents. I expected to get a table with number of cases for each row value, instead only the cases for the column variables are reported. Thus there is no information about the number of observations in each row.

```
cro_rpct(mtcars$am, list(mtcars$gear, total()))
```
So i tried to create a custom table, but I struggle to calculate the row sums of the valid cases.
The total column give the total number of cases including missing values:
```
mtcars$gear[c(1,3,7)] <- NA 
mtcars$am[c(4,5)] <- NA

mtcars %>%
  tab_cells(am) %>%
  tab_cols(gear, total()) %>%
  tab_stat_rpct() %>%
  tab_stat_cases() %>%
  tab_pivot(stat_position = "inside_columns")
```
I would expect to have valid row counts by default in `cro_rpct`

**Comment by gdemin** [comment]
Hi Sebastian,

With custom tables:
```R
mtcars$gear[c(1,3,7)] <- NA 
mtcars$am[c(4,5)] <- NA

mtcars %>%
    tab_cells(am) %>%
    tab_cols(gear) %>%
    tab_stat_rpct() %>%
    tab_cols(total(gear)) %>%
    tab_stat_cases() %>%
    tab_pivot(stat_position = "inside_columns")

 # |    |              | gear |       |       | #Total |
 # |    |              |    3 |     4 |     5 |        |
 # | -- | ------------ | ---- | ----- | ----- | ------ |
 # | am |            0 |   75 | 25.00 |       |     16 |
 # |    |            1 |      | 54.55 | 45.45 |     11 |
 # |    | #Total cases |   12 | 10.00 |  5.00 |     27 |
```
It seems I will introduce a new API because current syntax is not very flexible. But by now I don't know how exactly it will look like.

**Comment by sjewo** [comment]
Hi Gregory,

thanks - that worked!
