### ISSUE TITLE
Installing expss to use count_if

### ISSUE THREAD

**Issue by HadyShaaban** [gdemin/expss#50]
Hello team,
i'm trying to install expss but i'm facing this error
the code i'm using is as follows : 

```
install.packages("stringr")
install.packages("knitr")
install.packages("checkmate")
install.packages("htmlwidgets")
install.packages("htmltools")
install.packages("htmlTable")
install.packages("expss")
library(stringr)
library(knitr)
library(checkmate)
library(htmlwidgets)
library(htmltools)
library(htmlTable)
library(expss)
```
while getting library(htmlTable)
the error is : 
  installation of package ‘htmlTable’ had non-zero exit status
Error in library(htmlTable) : there is no package called ‘htmlTable’
library(expss)

Error: package or namespace load failed for ‘expss’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘htmlTable’
i much appreciate your support please in this issue

**Comment by gdemin** [comment]
Could you provide result of `sessionInfo()` function?

**Comment by gdemin** [comment]
I saw your topic - https://community.rstudio.com/t/installing-expss-package/46541/6
Please, restart your computer.
After restart don't run any R related software (R, RStudio and etc) and go to the library folder. Usually it is located in Program Files/R/library. 
Find folders htmlTable and expss and delete them if they exist.
After that run RStudio and install expss again.
VERY IMPORTANT. You will be asked to install packages from source or something like this. Say "No".
I hope these recommendations will help.

**Comment by HadyShaaban** [comment]
Hello @gdemin 
Thanks for your support.
I restarted my computer , deleted packages' folders from library directory , installed again them but same error appearing.
I also run sessioninfo() and following is its output
```
> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.1    DBI_1.0.0         tools_3.6.1       foreign_0.8-72    RPresto_1.3.3    
[6] Rcpp_1.0.2        data.table_1.12.6
```
Should i try something different ?
Much appreciated @gdemin

**Comment by HadyShaaban** [comment]
i tried on my personal laptop to install using the usual method install.packages("expss")
, it installed and worked perfectly , But couldn't why that occurring at work laptop. There is VPN and permission needed if we are opening exe files , but i have an authorization on the laptop as an administrator.

**Comment by gdemin** [comment]
Could you look for folders with 'LOCK' in the names in your library folder? Sometimes this folders remain after unfinished package installations and prevent repeated installation.
