### ISSUE TITLE
Problems with subgroup when having total() as banner

### ISSUE THREAD

**Issue by momo3246** [gdemin/expss#51]
I am having a problems with subgroup when I have set total() as one of my banners. Please see code below for more details:

```
mtcars %>%
  tab_cells(mpg) %>%
  tab_cols(total(), gear) %>%
  tab_subtotal_cols(1:2, 3:4, "5 and more" = greater(4)) %>%
  tab_stat_mean() %>%
  tab_pivot()
```

The results are a bit strange:

>  |                   |      | #Total |  2 | TOTAL #Total/2 |  3 |  4 | TOTAL 3/4 | 5 and more | Number of forward gears |     |               |       |      |
>  |                   |      |        |    |                |    |    |           |            |                     One | Two | TOTAL One/Two | Three | Four |
>  | ----------------- | ---- | ------ | -- | -------------- | -- | -- | --------- | ---------- | ----------------------- | --- | ------------- | ----- | ---- |
>  | Miles/(US) gallon | Mean |   20.1 |    |           20.1 |    |    |           |            |                         |     |               |  16.1 | 24.5 |
>                                        
>                   |      |            |
>  TOTAL Three/Four | Five | 5 and more |
>  ---------------- | ---- | ---------- |
>              19.9 | 21.4 |       21.4 |

but when I remove total() as banner, it looks totally fine, as follows:

```
mtcars %>%
  tab_cells(mpg) %>%
  tab_cols(gear) %>%
  tab_subtotal_cols(1:2, 3:4, "5 and more" = greater(4)) %>%
  tab_stat_mean() %>%
  tab_pivot()
```

Thanks so much in advance.

**Comment by gdemin** [comment]
`tab_subtotal_cols` applies `subtotal` to all column variables including total. And strange columns you see is empty subtotals for total variable. You need to apply subtotal only to gear variable as in the example below.

```R
data(mtcars)
mtcars %>%
    tab_cells(mpg) %>%
    tab_cols(total(), subtotal(gear, 1:2, 3:4, "5 and more" = greater(4))) %>%
    tab_stat_mean() %>%
    tab_pivot()
# |     |      | #Total |  1 |  2 | TOTAL 1/2 |    3 |    4 | TOTAL 3/4 |    5 | 5 and more |
# | --- | ---- | ------ | -- | -- | --------- | ---- | ---- | --------- | ---- | ---------- |
# | mpg | Mean |   20.1 |    |    |           | 16.1 | 24.5 |      19.9 | 21.4 |       21.4 |
```

**Comment by momo3246** [comment]
Thank you so much for your help!
