### ISSUE TITLE
Frequency and column percentages in a single table?

### ISSUE THREAD

**Issue by vinhdizzo** [gdemin/expss#54]
Hi there,

This isn't a bug report, but more of a naive question as I am new to the `expss` package.

Suppose I have a single categorical variable I want to summarize (eg, Ethnicity).  I can get frequencies using `tab_stat_cases` and I can get percentages using `tab_stat_cpct`.  I'd like to get both summaries in the same table, either as two columns or a single character column (eg, "frequency (percent)").

Do you have a suggestion on how to accomplish this?  I can't figure it out based on the current vignette.  Thank you for your assistance.

**Comment by vinhdizzo** [comment]
Sorry I just figured it out.  After creating objects using `tab_stat_cases` and `tab_stat_cpct`, I can use the `add_columns` function.

It didn't work for me before because I had the same column label in both objects.  When these were changed in both, I was able to get two columns in the same table.

**Comment by gdemin** [comment]
Hi,
`add_columns` is not the shortest path for this.
Canonical approach is to set argument in the `tab_pivot` function:
```R
data(mtcars)
mtcars = apply_labels(mtcars,
                      mpg = "Miles/(US) gallon",
                      cyl = "Number of cylinders",
                      disp = "Displacement (cu.in.)",
                      hp = "Gross horsepower",
                      drat = "Rear axle ratio",
                      wt = "Weight (1000 lbs)",
                      qsec = "1/4 mile time",
                      vs = "Engine",
                      vs = c("V-engine" = 0,
                             "Straight engine" = 1),
                      am = "Transmission",
                      am = c("Automatic" = 0,
                             "Manual"=1),
                      gear = "Number of forward gears",
                      carb = "Number of carburetors"
)

mtcars %>%
    tab_cells(am) %>%
    tab_cols(total(), vs) %>%
    tab_stat_cases(label = "count") %>%
    tab_stat_cpct(label = "col %") %>%
    tab_pivot(stat_position = "inside_columns")

# |              |              | #Total |       |   Engine |       |                 |       |
# |              |              |  count | col % | V-engine |       | Straight engine |       |
# |              |              |        |       |    count | col % |           count | col % |
# | ------------ | ------------ | ------ | ----- | -------- | ----- | --------------- | ----- |
# | Transmission |    Automatic |     19 |  59.4 |       12 |  66.7 |               7 |    50 |
# |              |       Manual |     13 |  40.6 |        6 |  33.3 |               7 |    50 |
# |              | #Total cases |     32 |  32.0 |       18 |  18.0 |              14 |    14 |
```
You can find a lot of examples in the help for `tab_pivot`. Just type in the console `?tab_pivot`.

**Comment by vinhdizzo** [comment]
Thanks so much for responding.  I knew there was a more elegant way to do this.  Still learning the `expss` framework for me to express what I want in my tables.
