### ISSUE TITLE
xl_write: different main_format styles for different tables in a list?

### ISSUE THREAD

**Issue by vinhdizzo** [gdemin/expss#58]
Hi,

Suppose I have a list of `e.table` objects, where some tables contain counts and some tables contain percentages.  Is it possible to use `xl_write` on a list of `e.table` objects to write all tables onto a single sheet, but with different `main_format` styles for different tables?

Thank you.

**Comment by gdemin** [comment]
Hi,
`main_format` will be applied to all tables in the list. However, if rows in the different tables has different statistic labels then you can specify special formats for them via `other_rows_formats` arguments.

**Comment by vinhdizzo** [comment]
Hmm, it appears `other_rows_formats` apply to rows based on the row labels.  I'm looking for a way to apply formats to specific tables.  I think I was hoping for something like a `tables_format` where the names in the named list corresponds to the names in the list of tables passed to `obj`.

Question: for the `additional_cells_formats` option, does the the row number and column number specified relative to the sheet?  Again, I am writing multiple tables to the same sheet.

Thank you.

**Comment by vinhdizzo** [comment]
I think I've figured it out:

```{r}
vars_decimal_regex <- '(Equivalent)|(OSH)'
vars_percent_regex <- 'Rates'
format_decimal <- function(tbl) {
  df <- matrix(data=0, nrow=nrow(tbl[, -1]), ncol=ncol(tbl[, -1]))

  if (str_detect(colnames(tbl)[2], vars_decimal_regex)) {
    results <- which(df == 0, arr.ind=TRUE)
  } else {
    results <- which(df != 0, arr.ind=TRUE)
  }
  
  return(results)
}
format_percent <- function(tbl) {
  df <- matrix(data=0, nrow=nrow(tbl[, -1]), ncol=ncol(tbl[, -1]))

  if (str_detect(colnames(tbl)[2], vars_percent_regex)) {
    results <- which(df == 0, arr.ind=TRUE)
  } else {
    results <- which(df != 0, arr.ind=TRUE)
  }
  
  return(results)
}
```

Then in my `xl_write` call, I pass:
```
, additional_cells_formats=list(
    list(format_decimal, createStyle(numFmt='0.00'))
  , list(format_percent, createStyle(numFmt='PERCENTAGE'))
```
