### ISSUE TITLE
Use of %merge%

### ISSUE THREAD

**Issue by robertogilsaura** [gdemin/expss#62]
Hi @gdemin 
I am trying to use the command% merge% and the results are not as expected. I expect a table with two columns where the first column is the cpct of the first variable and the second column is the cpct of the second variable.

Below is the code, but the new table keeps the two variables in rows. What could be the problem? What am I not observing?

```
data <- read_spss("~/_datos/66.nielsen/data.sav")
t1 <- data %>%
    tab_cells(P1) %>%
    tab_stat_cpct() %>%
    tab_pivot()
t2 <- data %>%
    tab_cells(mrset(..f(P2_R))) %>%
    tab_stat_cpct() %>%
    tab_pivot()
t1 %merge% t2
```
thanks in advance 
[data.zip](https://github.com/gdemin/expss/files/4487700/data.zip)

**Comment by robertogilsaura** [comment]
Hi @gdemin 
I found the solution, but I don't know if it is the most optimal solution.

```
t1 <- data %>%
    tab_cells('|'=P1) %>%
    tab_stat_cpct() %>%
    tab_pivot()
t2 <- data %>%
    tab_cells('|'=mrset(..f(P2_R))) %>%
    tab_stat_cpct() %>%
    tab_pivot()
t <- t1 %merge% t2
```
Diff is the var name in rows ... is it correct?

thanks in advance

**Comment by gdemin** [comment]
Yes, this is expected behavior. You need exact equality for merging - both variable and value label should be the same.
We can save a couple lines of code for this task:
```R
data %>%
    tab_cells('|'=P1) %>%
    tab_stat_cpct() %>%
    tab_cells('|'=mrset(..f(P2_R))) %>%
    tab_stat_cpct() %>%
    tab_pivot(stat_position = "inside_columns") # "inside_columns" make merge
```

**Comment by robertogilsaura** [comment]
Run properly. My problem was var_lab. Close issue.

thanks @gdemin
