### ISSUE TITLE
Error when using as_huxtable

### ISSUE THREAD

**Issue by przemo** [gdemin/expss#66]
Hi, Thanks again for great work on this package. I tried to use `as_huxtable` command  - from the Help documentation example - but I get the following error:
```
Error: ncol(obj1) is not NULL or ncol(obj2) is not NULL or ncol(obj1) not equal to ncol(obj2)
```
Do you happen to know what is the underlying issue?

**Comment by gdemin** [comment]
Hi,
Which version of the expss do you use? Try to update expss to version 0.10.5
There was incompatibility with new version of huxtable.  I hope I fixed it a couple of week ago.

**Comment by przemo** [comment]
My bad. I recently updated R and I thought I have the latest CRAN version of the package.
