### ISSUE TITLE
tabulation fails

### ISSUE THREAD

**Issue by ghost** [gdemin/expss#7]
The following code fails?

df <- data.frame(gender = sample(c("m", "f"), 1000, replace = TRUE),
                 agegroup = sample(c("young", "old", 1000, replace = TRUE)))

library(expss)

df %>% tab_cells(gender) %>% 
  tab_cols(total(), agegroup) %>% 
  tab_stat_cpct() %>% 
  tab_pivot()

**#> Error in data.table(cell_var, col_var, row_var): object '.R.listCopiesNamed' not found**  

Session Info:
#> Session info -------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.5.0 (2018-04-23)
#>  system   x86_64, linux-gnu           
#>  ui       X11                         
#>  language en_US:en                    
#>  collate  en_US.UTF-8                 
#>  tz       Europe/Stockholm            
#>  date     2018-05-20
#> Packages -----------------------------------------------------------------
#>  package     * version date       source        
#>  backports     1.1.2   2017-12-13 CRAN (R 3.5.0)
#>  base        * 3.5.0   2018-04-24 local         
#>  checkmate     1.8.5   2017-10-24 CRAN (R 3.5.0)
#>  compiler      3.5.0   2018-04-24 local         
#>  data.table    1.11.2  2018-05-08 CRAN (R 3.5.0)
#>  datasets    * 3.5.0   2018-04-24 local         
#>  devtools      1.13.5  2018-02-18 CRAN (R 3.5.0)
#>  digest        0.6.15  2018-01-28 CRAN (R 3.5.0)
#>  evaluate      0.10.1  2017-06-24 CRAN (R 3.5.0)
#>  expss       * 0.8.6   2018-01-24 CRAN (R 3.5.0)
#>  foreign       0.8-69  2017-06-21 CRAN (R 3.5.0)
#>  graphics    * 3.5.0   2018-04-24 local         
#>  grDevices   * 3.5.0   2018-04-24 local         
#>  htmlTable     1.11.2  2018-01-20 CRAN (R 3.5.0)
#>  htmltools     0.3.6   2017-04-28 CRAN (R 3.5.0)
#>  htmlwidgets   1.2     2018-04-19 CRAN (R 3.5.0)
#>  knitr         1.20    2018-02-20 CRAN (R 3.5.0)
#>  magrittr      1.5     2014-11-22 CRAN (R 3.5.0)
#>  matrixStats   0.53.1  2018-02-11 CRAN (R 3.5.0)
#>  memoise       1.1.0   2017-04-21 CRAN (R 3.5.0)
#>  methods     * 3.5.0   2018-04-24 local         
#>  Rcpp          0.12.16 2018-03-13 CRAN (R 3.5.0)
#>  rmarkdown     1.9     2018-03-01 CRAN (R 3.5.0)
#>  rprojroot     1.3-2   2018-01-03 CRAN (R 3.5.0)
#>  rstudioapi    0.7     2017-09-07 CRAN (R 3.5.0)
#>  stats       * 3.5.0   2018-04-24 local         
#>  stringi       1.2.2   2018-05-02 CRAN (R 3.5.0)
#>  stringr       1.3.1   2018-05-10 CRAN (R 3.5.0)
#>  tools         3.5.0   2018-04-24 local         
#>  utils       * 3.5.0   2018-04-24 local         
#>  withr         2.1.2   2018-03-15 CRAN (R 3.5.0)
#>  yaml          2.1.19  2018-05-01 CRAN (R 3.5.0)

**Comment by ogsj** [comment]
I backtracked to data.table 1.10.4 which works..

**Comment by gdemin** [comment]
It seems that data.table and expss should be build with the same version of R. So to avoid this error try to reinstall expss from CRAN. If it doesn't work, please, reopen issue.
