### ISSUE TITLE
significance tests with weighted data

### ISSUE THREAD

**Issue by zelihay** [gdemin/expss#75]
Hi Mr. Demin,

While I was able to generate counts&percents&means in a table by using "w_" codes,  in  
 tab_stat_cpct(total_statistic = "w_cpct"),
 tab_stat_fun("Mean" = w_mean,"Total" = w_n)

I couldn't able to produce a table with significant test results. How can I use the below functions for weighted data?

  tab_last_sig_means
  tab_last_sig_cpct
  tab_means_sig
  tab_last_round
  tab_last_add_sig_labels

Thanks for your help,

All my best,
Zeliha

**Comment by gdemin** [comment]
Hi, @zelihay 

You can do it the same way as in the issue #26.
However, you may need to specify weight and weighted valid N/cases for means and percents:
```R
library(expss)

value = sample(1:10, 625, replace=TRUE)
gender = sample(1:2, 625, replace=TRUE)
weight = runif(625) 
data <- data.frame(value,gender, weight)
var_lab(data$value) = 'Number of points'
var_lab(data$gender)= 'Gender'
val_lab(data$gender)= c ('male'=1, 'female'=2)


data %>%
    tab_cells(value) %>%
    tab_cols(total(), gender) %>%
    tab_weight(weight) %>% # !! specify weight
    tab_stat_cpct(total_statistic = "w_cases") %>% # !! weighted total
    tab_cells(value=na_if(value, gt(10))) %>%
    tab_last_round() %>% 
    tab_last_add_sig_labels() %>% 
    tab_stat_mean_sd_n(weighted_valid_n = TRUE) %>% # !! weighted valid N
    tab_last_sig_means() %>% 
    tab_pivot()
```

**Comment by zelihay** [comment]
Thanks a lot!
