### ISSUE TITLE
Potential Bug weighted Mean/SD/Var

### ISSUE THREAD

**Issue by Waschoi** [gdemin/expss#77]
Hi,

I found I potential Bug, but I am not sure where there error lies, see this example at matrixStats
https://github.com/HenrikBengtsson/matrixStats/issues/198#issue-785854244

Regardless of whether MatrixStats has an bug, your functions within expss give different results:

data%>%
        summarise_at(vars(b16b1), list(
        mean  = ~weighted.mean(., w = wph, na.rm = T),
        mean2 = ~expss::w_mean(., weight = wph),
        mean3 = ~matrixStats::weightedMean(., weight = wph, na.rm = T, refine = T),
        mean4 = ~sjstats::weighted_mean(x=., weights = wph),
        n = ~n()))

       # A tibble: 1 x 5
       mean mean2 mean3 mean4     n
      <dbl> <dbl> <dbl> <dbl> <int>
        2.46  2.46  2.55  2.46    20

If I use  expss::tab_stat_mean() within a pipe the result would be 2.55
If I use w_mean it would be 2.46. 

Hope this is clear.

Thanks for the last fix I reported 👍

**Comment by gdemin** [comment]
Hi, 

For matrixStats there is no `weights` arguments. It's called `w`. `matrixStats::weightedMean(as.double(data$b16b1), w = data$wph)` gives correct result.

**Comment by Waschoi** [comment]
I'll have to check again. Maybe I did something wrong. Sorry and thanks for the response.
