### ISSUE TITLE
Unable to install "expss" think there's an error installing knitr and xfun

### ISSUE THREAD

**Issue by OishiGoswami** [gdemin/expss#80]
Hello!

When I tried to install "expss" , and replying yes to installing from sources the package which needs compilation, I get:

"* installing *source* package ‘xfun’ ...
** package ‘xfun’ successfully unpacked and MD5 sums checked
** libs
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
ERROR: compilation failed for package ‘xfun’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/xfun’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/xfun’
Warning in install.packages :
  installation of package ‘xfun’ had non-zero exit status
* installing *source* package ‘knitr’ ...
** package ‘knitr’ successfully unpacked and MD5 sums checked
** R
** demo
** inst
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘xfun’ 0.12 is being loaded, but >= 0.19 is required
ERROR: lazy loading failed for package ‘knitr’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/knitr’
Warning in install.packages :
  installation of package ‘knitr’ had non-zero exit status
ERROR: dependency ‘knitr’ is not available for package ‘htmlTable’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/htmlTable’
Warning in install.packages :
  installation of package ‘htmlTable’ had non-zero exit status
ERROR: dependency ‘htmlTable’ is not available for package ‘expss’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/expss’
Warning in install.packages :
  installation of package ‘expss’ had non-zero exit status "

When I tried to install and update "xfun" I get:
" * installing *source* package ‘xfun’ ...
** package ‘xfun’ successfully unpacked and MD5 sums checked
** libs
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
ERROR: compilation failed for package ‘xfun’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/xfun’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/xfun’
Warning in install.packages :
  installation of package ‘xfun’ had non-zero exit status "

I'm running version 0.12 of xfun.

Thank you so much for helping out!

**Comment by gdemin** [comment]
Hi,
Sorry, but I it seems its better to file this issue to `xfun` package: https://github.com/yihui/xfun/issues
I don't directly use xfun package. I suppose it needed for knitr.
