### ISSUE TITLE
Creating filtered versions of crosstabs within main code

### ISSUE THREAD

**Issue by aksh1985** [gdemin/expss#82]
``I work in market research and expss has been a revelation for running crosstabs! However there are a few use cases where I feel there could be room to streamline the process.

I might be wrong, and expss might already to this but I couldn't find anything in the documentation. 

One of the most common use cases in research is creating filtered versions of crosstabs on a specific subset of question sample. 

So imagine, we have a table set which looks like
`data_table <- df %>%
  tab_cells(Q1, Q2, Q3
) %>%
    tab_cols(total(), Q4) %>%
  tab_stat_cpct() %>%
  tab_pivot()`

Often it will be the case that I would want a specific table, say Q3 in that table set duplicated for a specific subgroup say Q5 = condition.
Right now I have a create a new data frame subsetting the original data on Q5 condition and then run another set of tables just for what I need but was thinking it would be great to be able to do this inline. e.g.

`data_table <- df %>%
  tab_cells(Q1, Q2, Q3, Q3 %filter% Q5 == condition)
) %>%
    tab_cols(total(), Q4) %>%
  tab_stat_cpct() %>%
  tab_pivot()`

What do you think?

Thanks!

**Comment by gdemin** [comment]
Hi,
It seems should do the trick:
```
data_table <- df %>% tab_cells(Q1, Q2, Q3, mis_val(Q3, Q5 == condition)) %>% tab_cols(total(), Q4) %>% tab_stat_cpct() %>% tab_pivot()
```

**Comment by aksh1985** [comment]
Thanks! That's a good shout. Can't test atm but should work. But I guess since mis val would blank out the cases you want to keep, you have to invert the condition logic which can get a bit convoluted.

**Comment by gdemin** [comment]
Yes, I made a typo, condition logic should be inverted. 
More verbose solution with straightforward logic:
```R
data_table <- df %>%
 tab_cells(Q1, Q2, Q3) %>% 
 tab_cols(total(), Q4) %>%
 tab_stat_cpct() %>%
 tab_subgroup(Q5 == condition)
 tab_cells(Q3)) %>% 
 tab_stat_cpct() %>%
 tab_pivot()

**Comment by aksh1985** [comment]
Wonderful! I completely missed that element in the documentation. Is there a "nice" way to removing the subgroup condition so that we go back to total sample for crosstabs afterwards? Or would I need to use subgroup with trivial condition like !(is.na) on one of the complete columns?

**Comment by gdemin** [comment]
Empty argument - `tab_subgroup()` - will be enough for total sample.

**Comment by aksh1985** [comment]
Thanks!
