### ISSUE TITLE
Error in package download

### ISSUE THREAD

**Issue by Ivnstts** [gdemin/expss#84]
Hello, I'm new to R, and I don't know how to solve this issue.

> library(expss)
Error : package or namespace load failed for ‘expss’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace ‘xfun’ 0.16 is already loaded, but >= 0.19 is required

Thanks for the support

**Comment by gdemin** [comment]
Hi,
Try to restart R and than install 'xfun' package separately and then install 'expss'. I hope, it helps.
