### ISSUE TITLE
Merge cpct & rpct in crosstab

### ISSUE THREAD

**Issue by robertogilsaura** [gdemin/expss#85]
Hi @gdemin, I hope you're well ...

I have a doubt to get a crosstab where the total column are column percentages ( u_cpct), and the rest of the table are row percentages (u_rpct) . I have seen that there is the possibility of applying the tab_total_statistic () function, but I see it always applied in total row. Here, I have a short example where I can apply ...
```
library(expss)
x <- c(1,3,5,99,3,2,1)
y <- c(1,1,2,2,3,3,4)
df <- data.frame(x,y)
var_lab(df$x) <- 'x'
df %>%
	tab_cols(total(), y) %>%
	tab_cells(x) %>%
	tab_stat_rpct() %>%
	tab_cells(na_if(x, gt(10))) %>%
	tab_stat_mean() %>%
	tab_pivot()
```
How should I change my simple coding?

Thanks in advance ...

**Comment by gdemin** [comment]
Hi, @robertogilsaura 
Rather wordy code:

```R
df %>%
    tab_cols(total()) %>%
    tab_cells(x) %>%
    tab_stat_cpct() %>%
    tab_cells(na_if(x, gt(10))) %>%
    tab_stat_mean() %>%
    tab_last_vstack() %>% 
    tab_cols(y) %>%
    tab_cells(x) %>%
    tab_stat_rpct() %>%
    tab_cells(na_if(x, gt(10))) %>%
    tab_stat_mean() %>%
    tab_last_vstack() %>% 
    tab_pivot(stat_position = "inside_columns")
```

**Comment by robertogilsaura** [comment]
Hi @gdemin, a lot of thanks; code runs perfectly.

I didn't know and I have learned use of `tab_last_vstack` twice (or more) mixed with `stat_position = "inside_columns"` in one crosstab. 

I have test this code too and runs ok

```
df %>%
     tab_cols(total()) %>%
     tab_cells(x) %>%
     tab_stat_cpct() %>%
     tab_cells(na_if(x, gt(10))) %>%
     tab_stat_mean() %>%
     tab_last_vstack() %>% 
     tab_stat_sd() %>%
     tab_last_vstack() %>% 
     tab_cols(y) %>%
     tab_cells(x) %>%
     tab_stat_rpct() %>%
     tab_cells(na_if(x, gt(10))) %>%
     tab_stat_mean() %>%
     tab_last_vstack() %>% 
     tab_stat_sd() %>%
     tab_last_vstack() %>% 
     tab_pivot(stat_position = "inside_columns")

```

Regards,
