### ISSUE TITLE
allow use.NA option for cro?

### ISSUE THREAD

**Issue by zouw2** [gdemin/expss#9]
can we have a similar argument like table(, use.NA='') for cro(). It seems the current cro() will drop NA values.
thanks
wei

**Comment by gdemin** [comment]
By now I don't want to add such argument because `cro` already have a lot of arguments and additional options will make it overcomplicated and less manageable.
There is a special function for such cases: `if_na`.
```R
library(expss)
set.seed(123) # reporducability
vec = sample(c(1:3, NA), 100, replace = TRUE)
var_lab(vec) = "Vector with NA"
cro(vec) # no NA

if_na(vec, "<NA>") %>%  cro() # replace NA with "<NA>"
if_na(factor(vec), "<NA>") %>% cro() # we can use `factor` if we want to preserve order of values
```

**Comment by zouw2** [comment]
Ok, thanks!
wei
