### ISSUE TITLE
What happened to vlookup?

### ISSUE THREAD

**Issue by DrMattG** [gdemin/expss#91]
vlookup was a really useful function. I was just wondering what happened to it? It doesn't appear to be in the latest CRAN version. 

I get this error message: 
Error: 'vlookup' is not an exported object from 'namespace:expss'

**Comment by gdemin** [comment]
`vlookup` is moved to maditr on which expss depends on now. You can change `expss::vlookup` to `maditr::vlookup`. 
Sorry for inconveniences.
If it is a real issue I can reexport vlookup from maditr to expss in the future version.
