### ISSUE TITLE
expss--where did it go?

### ISSUE THREAD

**Issue by nycaej** [gdemin/expss#97]
> install.packages("expss")
Installing package into ‘/home/health.dohmh.nycnet/ajordan2/R/x86_64-redhat-linux-gnu-library/3.3’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘expss’ is not available (for R version 3.5.2)

**Comment by gdemin** [comment]
Hi,
expss requres R (≥ 3.6.0)
